colors = {
    'slate gray (Muted Pastels Background)': '#2C2C2C',
    'light gray (Muted Pastels Text)': '#E4E4E4',
    'light cyan (Muted Pastels Accent 1)': '#A8DADC',
    'soft pink (Muted Pastels Accent 2)': '#FFC1CC',
    'lavender (Muted Pastels Button/CTA)': '#B39CD0',
    'charcoal black (Monochromatic Background)': '#121212',
    'light gray (Monochromatic Text)': '#E0E0E0',
    'medium gray (Monochromatic Secondary Text)': '#B0B0B0',
    'dark gray (Monochromatic Borders/Dividers)': '#444444',
    'soft gray (Monochromatic Accent)': '#888888',
    'almost black (Neon Highlights Background)': '#0D0D0D',
    'pure white (Neon Highlights Text)': '#FFFFFF',
    'neon green (Neon Highlights Accent 1)': '#00FF85',
    'electric blue (Neon Highlights Accent 2)': '#1E90FF',
    'vivid pink (Neon Highlights Hover Effects)': '#FF0099',
    'soft black (Warm Tones Background)': '#1C1C1C',
    'warm beige (Warm Tones Text)': '#F5E8D8',
    'muted coral (Warm Tones Accent 1)': '#FF6F61',
    'golden yellow (Warm Tones Accent 2)': '#DAA520',
    'burnt orange (Warm Tones Hover Effects)': '#FF4500',
    'rich black (Jewel Tones Background)': '#1A1A1A',
    'off-white (Jewel Tones Text)': '#F0F0F0',
    'dark teal (Jewel Tones Accent 1)': '#004D61',
    'deep ruby (Jewel Tones Accent 2)': '#822659',
    'forest green (Jewel Tones Button/CTA)': '#3E5641',
    'dark gray (Contrasting Vibrancy Background)': '#181818',
    'off-white (Contrasting Vibrancy Text)': '#F7F7F7',
    'vibrant orange (Contrasting Vibrancy Accent 1)': '#FF5722',
    'deep purple (Contrasting Vibrancy Accent 2)': '#673AB7',
    'bright yellow (Contrasting Vibrancy Hover Effects)': '#FFEB3B'
}

# US States dictionary: Full Name -> Two-Letter Acronym
us_states = { 
    'Alabama': 'AL',
    'Alaska': 'AK',
    'Arizona': 'AZ',
    'Arkansas': 'AR',
    'California': 'CA',
    'Colorado': 'CO',
    'Connecticut': 'CT',
    'Delaware': 'DE',
    'Florida': 'FL',
    'Georgia': 'GA',
    'Hawaii': 'HI',
    'Idaho': 'ID',
    'Illinois': 'IL',
    'Indiana': 'IN',
    'Iowa': 'IA',
    'Kansas': 'KS',
    'Kentucky': 'KY',
    'Louisiana': 'LA',
    'Maine': 'ME',
    'Maryland': 'MD',
    'Massachusetts': 'MA',
    'Michigan': 'MI',
    'Minnesota': 'MN',
    'Mississippi': 'MS',
    'Missouri': 'MO',
    'Montana': 'MT',
    'Nebraska': 'NE',
    'Nevada': 'NV',
    'New Hampshire': 'NH',
    'New Jersey': 'NJ',
    'New Mexico': 'NM',
    'New York': 'NY',
    'North Carolina': 'NC',
    'North Dakota': 'ND',
    'Ohio': 'OH',
    'Oklahoma': 'OK',
    'Oregon': 'OR',
    'Pennsylvania': 'PA',
    'Rhode Island': 'RI',
    'South Carolina': 'SC',
    'South Dakota': 'SD',
    'Tennessee': 'TN',
    'Texas': 'TX',
    'Utah': 'UT',
    'Vermont': 'VT',
    'Virginia': 'VA',
    'Washington': 'WA',
    'West Virginia': 'WV',
    'Wisconsin': 'WI',
    'Wyoming': 'WY',
    'District of Columbia': 'DC'
}

